#!/usr/local/cpanel/3rdparty/bin/perl
# cpanel - ea4-tool-post-update                 Copyright(c) 2022 cPanel, L.L.C.
#                                                           All rights Reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

package ea_passenger_src::ea4_tool_post_update;

use strict;
use warnings;

use lib "../ea-tools/lib/ea4_tool";    # assumes ea-tools is checked out next to this repo
use ea4_tool::util ();
use ea4_tool::util::gitapi;
use File::chdir;
use Path::Tiny;

exit( run(@ARGV) ? 0 : 1 ) if !caller;

sub run {
    my ( $old_ver, $new_ver ) = @_;

    my $case = "ZC-12636";
    my $et        = '/root/git/ea-tools/bin/ea4-tool';
    my $changelog = "ea-passenger-src was updated from v$old_ver to v$new_ver";

    for my $repo (qw(ea-apache24-mod-passenger ea-nginx-passenger)) {
        my $cmd = "$et change $repo $case '$changelog' $new_ver";
        system($cmd) && warn "Could not update ‘$repo’! This will need done manually:\n\t$cmd\n";
        _generate_pr( $repo, $changelog );

        print "Done!\n";
    }

    return 1;
}

sub _generate_pr {
    my ( $repo, $changelog ) = @_;

    my $repo_path = ea4_tool::util::get_path_of_repo($repo);
    local $CWD = $repo_path;

    my $git    = ea4_tool::util::git($CWD);
    my $branch = $git->current_branch();

    my $case;
    if ( $branch =~ m/^(.*)-\Q$repo\E$/ ) {
        $case = $1;
    }
    die "Could not determine case" if !$case;

    ea4_tool::util::pushup( $git, "$branch" );

    my $gitapi = ea4_tool::util::gitapi->new();
    my $title  = "$case: $changelog";

    $gitapi->create_pull_request( $repo => $title, $branch => "main" );

    return;
}

1;
